module.exports = [
    'Baden-Württemberg',
    'Bavaria',
    'Augsburg in Bavaria',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hesse',
    'Mecklenburg-Vorpommern',
    'Lower Saxony',
    'North Rhine-Westphalia',
    'Rhineland-Palatinate',
    'Saarland',
    'Saxony',
    'Saxony-Anhalt',
    'Schleswig-Holstein',
    'Thuringia',
    'Eichsfeld Catholic district'
];
