module.exports = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'North Carolina',
    'South Carolina',
    'Colorado',
    'Connecticut',
    'North Dakota',
    'South Dakota',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New York',
    'New Mexico',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'West Virginia',
    'Washington',
    'Wisconsin',
    'Wyoming'
];
